name: Build docker image and Deploy on VM

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t narainad308/video-proctoring-backend:latest .

      - name: Push Docker image
        run: |
          docker push narainad308/video-proctoring-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull narainad308/video-proctoring-backend:latest
            sudo docker stop video-proctoring-backend || true
            sudo docker rm video-proctoring-backend || true
            sudo docker run -d --restart unless-stopped --name video-proctoring-backend -p 5000:4000 narainad308/video-proctoring-backend:latest

